apiVersion: v2
name: cert-manager
description: An umbrella chart for deploying cert-manager
version: 0.0.1
dependencies:
  - name: cert-manager
    version: 1.18.2
    repository: https://charts.jetstack.io